server:
  port: 8081

spring:
  application:
    name: backend
  profiles:
    include: secrets

  datasource:
    url: jdbc:h2:mem:myappdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  access-token-expiration-ms: 86400000
  refresh-token-expiration-ms: 2592000000

cloudflare:
  r2:
    bucket-name: "my-app"
    public-base-url: "https://pub-e8e8e80b8f704c9d88967085b54d6936.r2.dev"