server:
  port: 8081

spring:
  config:
    import: optional:application-secrets.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/myapp
    username: myuser
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 100

jwt:
  access-token-expiration-ms: 86400000
  refresh-token-expiration-ms: 2592000000

cloudflare:
  r2:
    bucket-name: "my-app"
    public-base-url: "https://pub-e8e8e80b8f704c9d88967085b54d6936.r2.dev"